# Generated by Django 5.2 on 2025-11-06 17:33

import apps.core.storages
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('path', models.FileField(blank=True, editable=False, max_length=255, null=True, storage=apps.core.storages.UUIDS3Storage(), upload_to='', verbose_name='Path')),
                ('name', models.CharField(editable=False, max_length=255, verbose_name='Nome')),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável')),
            ],
            options={
                'verbose_name': 'Upload de arquivo',
                'verbose_name_plural': 'Upload de arquivos',
            },
        ),
    ]
