# Generated by Django 5.2 on 2025-07-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, help_text='Nome completo do usuário.', max_length=255, null=True, verbose_name='Nome'),
        ),
    ]
